USE [master]
GO
/****** Object:  Database [NASEEJ]    Script Date: 2/9/2025 12:33:51 PM ******/
CREATE DATABASE [NASEEJ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NASEEJ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NASEEJ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NASEEJ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NASEEJ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [NASEEJ] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NASEEJ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NASEEJ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NASEEJ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NASEEJ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NASEEJ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NASEEJ] SET ARITHABORT OFF 
GO
ALTER DATABASE [NASEEJ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NASEEJ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NASEEJ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NASEEJ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NASEEJ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NASEEJ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NASEEJ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NASEEJ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NASEEJ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NASEEJ] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NASEEJ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NASEEJ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NASEEJ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NASEEJ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NASEEJ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NASEEJ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NASEEJ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NASEEJ] SET RECOVERY FULL 
GO
ALTER DATABASE [NASEEJ] SET  MULTI_USER 
GO
ALTER DATABASE [NASEEJ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NASEEJ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NASEEJ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NASEEJ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NASEEJ] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NASEEJ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'NASEEJ', N'ON'
GO
ALTER DATABASE [NASEEJ] SET QUERY_STORE = ON
GO
ALTER DATABASE [NASEEJ] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [NASEEJ]
GO
/****** Object:  Table [dbo].[Blogs]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blogs](
	[BlogID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[BlogDate] [datetime] NOT NULL,
	[EmployeeId] [int] NULL,
	[Image] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[BlogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ContactUs]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContactUs](
	[ContactID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[Subject] [nvarchar](max) NULL,
	[Message] [nvarchar](max) NULL,
	[MessageReply] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEES]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEES](
	[EmployeeId] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[IsAdmin] [bit] NULL,
	[Image] [nvarchar](max) NULL,
	[Scope] [nvarchar](100) NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[PasswordSalt] [nvarchar](max) NULL,
	[Otp] [nvarchar](50) NULL,
	[IsUsed] [bit] NULL,
	[OtpGeneratedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Newslatter]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Newslatter](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[User_Email] [nvarchar](50) NOT NULL,
	[Admin_Replay] [nvarchar](max) NULL,
	[Status] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_User_Email] UNIQUE NONCLUSTERED 
(
	[User_Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROJECT]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROJECT](
	[ProjectId] [int] IDENTITY(1,1) NOT NULL,
	[ProjectName] [nvarchar](100) NULL,
	[ProjectImage] [nvarchar](max) NULL,
	[ProjectDescription] [nvarchar](max) NULL,
	[EmployeeId] [int] NULL,
	[IsAccept] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REQUEST]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REQUEST](
	[RequestId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[ServiceId] [int] NULL,
	[RequestDate] [datetime] NULL,
	[description] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[RequestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICES]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICES](
	[ServiceId] [int] IDENTITY(1,1) NOT NULL,
	[ServiceName] [nvarchar](100) NULL,
	[ServiceDescription] [nvarchar](max) NULL,
	[ServiceImage] [nvarchar](max) NULL,
	[ServiceDate] [datetime] NULL,
	[EmployeeId] [int] NULL,
	[IsAccept] [nvarchar](50) NULL,
	[fromage] [int] NULL,
	[toage] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ServiceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Testimonials]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Testimonials](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[Firstname] [nvarchar](255) NULL,
	[lastname] [nvarchar](255) NULL,
	[theTestimonials] [nvarchar](max) NULL,
	[isaccepted] [bit] NULL,
	[Email] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[Nationality] [nvarchar](50) NULL,
	[Degree] [nvarchar](100) NULL,
	[Governorate] [nvarchar](100) NULL,
	[Age] [int] NULL,
	[JoinDate] [datetime] NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[PasswordSalt] [nvarchar](max) NULL,
	[Email] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WomenRight]    Script Date: 2/9/2025 12:33:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WomenRight](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
	[AgeGroup] [nvarchar](50) NOT NULL,
	[EducationLevel] [nvarchar](100) NOT NULL,
	[CurrentlyWorking] [nvarchar](40) NOT NULL,
	[WorkType] [nvarchar](70) NOT NULL,
	[Challenges] [nvarchar](max) NULL,
	[CommunityCultureImpact] [nvarchar](40) NULL,
	[SubmissionDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IsUsed]  DEFAULT ((0)) FOR [IsUsed]
GO
ALTER TABLE [dbo].[Newslatter] ADD  DEFAULT ((0)) FOR [Status]
GO
ALTER TABLE [dbo].[Newslatter] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[PROJECT] ADD  DEFAULT ('Pinding') FOR [IsAccept]
GO
ALTER TABLE [dbo].[SERVICES] ADD  DEFAULT ('Pinding') FOR [IsAccept]
GO
ALTER TABLE [dbo].[Testimonials] ADD  DEFAULT ((0)) FOR [isaccepted]
GO
ALTER TABLE [dbo].[WomenRight] ADD  DEFAULT (getdate()) FOR [SubmissionDate]
GO
ALTER TABLE [dbo].[Blogs]  WITH CHECK ADD FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEES] ([EmployeeId])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[PROJECT]  WITH CHECK ADD  CONSTRAINT [FK__PROJECT__Employe] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEES] ([EmployeeId])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[PROJECT] CHECK CONSTRAINT [FK__PROJECT__Employe]
GO
ALTER TABLE [dbo].[REQUEST]  WITH NOCHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICES] ([ServiceId])
GO
ALTER TABLE [dbo].[REQUEST]  WITH NOCHECK ADD  CONSTRAINT [FK__REQUEST__Service__48CFD7E] FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICES] ([ServiceId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[REQUEST] CHECK CONSTRAINT [FK__REQUEST__Service__48CFD7E]
GO
ALTER TABLE [dbo].[REQUEST]  WITH NOCHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
GO
ALTER TABLE [dbo].[SERVICES]  WITH CHECK ADD  CONSTRAINT [FK_Services_Employees] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEES] ([EmployeeId])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[SERVICES] CHECK CONSTRAINT [FK_Services_Employees]
GO
ALTER TABLE [dbo].[Testimonials]  WITH NOCHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
GO
ALTER TABLE [dbo].[PROJECT]  WITH NOCHECK ADD CHECK  (([IsAccept]='Pinding' OR [IsAccept]='Accept'))
GO
ALTER TABLE [dbo].[SERVICES]  WITH NOCHECK ADD CHECK  (([IsAccept]='Pinding' OR [IsAccept]='Accept'))
GO
USE [master]
GO
ALTER DATABASE [NASEEJ] SET  READ_WRITE 
GO
